version: "3.9"
services:
  db:
    image: postgres:13-alpine
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data



volumes:
  postgres_data:
  cache: