"""Model Change

Revision ID: 34c6659c25c6
Revises: 3fcdb71e932a
Create Date: 2022-10-31 15:44:37.726916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c6659c25c6'
down_revision = '3fcdb71e932a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_review',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'review_id')
    )
    op.drop_constraint('products_review_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'review_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('products_review_id_fkey', 'products', 'reviews', ['review_id'], ['id'])
    op.drop_table('product_review')
    # ### end Alembic commands ###
