"""Model Change

Revision ID: 3fcdb71e932a
Revises: 4f7c4fc00028
Create Date: 2022-10-31 15:40:39.131317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcdb71e932a'
down_revision = '4f7c4fc00028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('review_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'reviews', ['review_id'], ['id'])
    op.drop_constraint('reviews_product_id_fkey', 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('reviews_product_id_fkey', 'reviews', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'review_id')
    # ### end Alembic commands ###
