"""Model Change

Revision ID: 486cd61664ef
Revises: 4516b91ced1b
Create Date: 2022-10-31 17:35:09.401760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486cd61664ef'
down_revision = '4516b91ced1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_review_id', table_name='product_review')
    op.drop_column('product_review', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_review', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_product_review_id', 'product_review', ['id'], unique=False)
    # ### end Alembic commands ###
