"""Model Change

Revision ID: 4f7c4fc00028
Revises: 82d3d9682ade
Create Date: 2022-10-31 15:33:29.691741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7c4fc00028'
down_revision = '82d3d9682ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'product_id')
    # ### end Alembic commands ###
