"""Model Change

Revision ID: ce54b466f4b9
Revises: 0a047b541114
Create Date: 2022-10-31 14:31:11.586760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce54b466f4b9'
down_revision = '0a047b541114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_review')
    op.add_column('reviews', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'product_id')
    op.create_table('product_review',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_review_product_id_fkey'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name='product_review_review_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', 'review_id', name='product_review_pkey')
    )
    # ### end Alembic commands ###
