"""Minor

Revision ID: f3cdcca2ee5d
Revises: 8daf634f0b32
Create Date: 2022-10-31 09:22:51.811105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cdcca2ee5d'
down_revision = '8daf634f0b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reviews_review_key', 'reviews', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('reviews_review_key', 'reviews', ['review'])
    # ### end Alembic commands ###
